### PR TITLE
Allowing a version/branch string to be parsed in download url

### LINKED ISSUE #16: Support branches
When using `template use repo/repo` - support `repo/repo:branch`

### PR DESCRIPTION
**Pull request by rawkode**
Closes #16

### CODE REVIEW

**Comment by tmrts** [comment]
@rawkode nice! thank you. I can't merge it though it says that the branch has conflicts, try a rebase?

**Comment by rawkode** [comment]
Weird! I did pull before submitting. I'll rebase when I'm off train. No problem

**Comment by rawkode** [comment]
Sorted

**Comment by tmrts** [comment]
@rawkode merged now thanks.

Branch specification is enabled now 👏

**Pull request merged**
